# Generated by Django 3.0.2 on 2020-03-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app21', '0002_auto_20200310_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmodel',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
