# Generated by Django 3.0.2 on 2020-03-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app21', '0003_auto_20200311_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmodel',
            name='password',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
